server:
  port: 8081
spring:
  application:
    name: SpotLuxe
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spotluxe?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: 192.168.25.130
    port: 6379
    password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.SpotLuxe.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
logging:
  level:
    com.SpotLuxe: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" # 控制台输出格式