---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ZIO.
--- DateTime: 2025/4/2 19:03
---
if(redis.call('get',KEYS[1])==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0